### ISSUE TITLE
Generate a system able to autorotate pictures

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#31]
Many pictures sent to Open Food Facts are not properly rotated. Create a system able to autorotate pictures.

![image](https://user-images.githubusercontent.com/1689815/36934201-500f8cca-1ee6-11e8-897c-437b67c899aa.png)

**Comment by yashpungaliya** [comment]
This looks like a rather interesting problem because the orientation of an image can be arbitrary and can be decided only based on the content of the image. It would not always mean that the image should be in a Landscape/Portrait mode because the text on the image will determine its orientation.
 
For this, I suggest that we can use CV to detect a small sample of text on the image(even detecting the orientation of a character might work and make our lives easier). Based on this ,we rotate the image..

Possible issues-
1.Text is aligned both ways on the image.
2.Text is absent.
3.Vertically aligned text.

**Comment by teolemon** [comment]
@stephanegigandet Can we generate a dataset with a day's worth of selected ingredient pictures ?

**Comment by teolemon** [comment]
@stephanegigandet It has to be recent pictures, so that many ingredient lists are still poorly rotated.

**Comment by JyotsanaS** [comment]
@teolemon I have created a small dataset of about 27 images which need rotation for ingredients and nutrition table. 
https://github.com/JyotsanaS/off/tree/master/autorotate

**Comment by ashishkumar1550** [comment]
If no one is working on this issue, can I start working on it?

**Comment by Anubhav-Bhargava** [comment]
This problem is similar to this [StrackOverflow Question](https://stackoverflow.com/questions/46731947/detect-angle-and-rotate-an-image-in-python). 
Tried the script on bunch of different images provided by @JyotsanaS. 
The results are good but it sometimes detects the angle to be negative of the actual value (and vice versa), so the image is sometimes rotated in opposite direction.

**Comment by ashishkumar1550** [comment]
@Anubhav-Bhargava I think using image processing techniques might not perform well on diverse data but I can be wrong here. I think this problem can be better solved using deep learning, I did see some papers on it which I am going to try now, lets see what technique works out better to solve this problem.

**Comment by llucifer97** [comment]
Hi @teolemon if no one is working on this issue i would like to solve this issue?

**Comment by raphael0202** [comment]
@teolemon Implemented in Robotoff, we should discuss how to use this feature in OFF

**Comment by teolemon** [comment]
@raphael0202 Perhaps in HungerGames ?
